Refactor Inicial (Clean Code)
elagarrigue/AyDS23-Winchester1 pull request #6
Opened 2023-04-27 01:57 UTC by valenbarrera

2023-04-27 17:44 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +class DataBase(context: Context?) : SQLiteOpenHelper(context, "dictionary.db", null, 1) {
nombre de la base de datos y version deberian ser constantes tambien

2023-04-27 17:54 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (items.isEmpty()) null else items[0]
items.firstOrNull() ?: ""

2023-04-27 21:09 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        dataBase.saveArtist("test", "sarasa")
esto no va

2023-04-27 21:09 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        createWikipediaAPI()
esto no es responsabilidad del open, deberia estar en el onCreate

2023-04-27 21:15 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        dataBase = DataBase(this)
la creacion de la base de datos y de wikipedia api, deberia estar en un metodo separado, es un inicializador

2023-04-27 21:15 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        open(intent.getStringExtra("artistName"))
no es necesario pasarle el parametro intent
ademas el artistName deberia ser constante..

2023-04-27 21:23 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var dataBase: DataBase
deben definirse como val, igual que wikipedia API

2023-04-27 21:26 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun createRetrofit(): Retrofit {
utilizar funcion inline

2023-04-27 21:28 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            infoSong = infoSong?.let { "[*]$it" } ?: handleNullInfoSong(artistName)
estan haciendo manejo de datos dentro de la logica de vista, hay que sacar en funciones

2023-04-27 21:31 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun handleNullInfoSongAux(artistName: String?): String {
en el nombre de la funcion "AUX"?

2023-04-27 21:39 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return jobj?.get(QUERY)?.asJsonObject
aca es necesario introducir variables intermedias para que se pueda entender

2023-04-27 21:39 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return query?.get(SEARCH)?.asJsonArray?.get(0)?.asJsonObject?.get(SNIPPET)
aca es necesario introducir variables intermedias para que se pueda entender

2023-04-27 21:39 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return query?.get(SEARCH)?.asJsonArray?.get(0)?.asJsonObject?.get(PAGE_ID)
aca es necesario introducir variables intermedias para que se pueda entender

2023-04-27 21:40 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +class OtherInfoWindow : AppCompatActivity() {
Tienen muchos "?", deberian tratar de resolver de otra manera lo null

2023-04-27 21:42 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        var infoSong = ""
hay que tratar de usar el val
el nombre "handleNullInfoSong", no es representativo del metodo...

2023-04-27 21:43 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        setListener(urlString)
manejen el side effect

2023-04-28 10:43 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
Distintos niveles de abstracción:

findViewById -> definir una propiedad e inicializarla
setOnClickListener
Resolver el intent y hacer el startActivity -> mover a sub función

2023-04-28 12:23 UTC, Luchyluz requested changes
trabajen sobre los comentarios, si es necesario consulten...

Para poder sacar lógica de vista del algoritmo repository, la función debería retornar un objeto que contenga el string de información, url, y una bandera indicando si estaba en la db o no. Si bien en el enunciado se pide no crear nuevas clases (reestructurando la clase actual), esta nueva clase de dominio es necesaria.

2023-04-30 19:23 UTC, MateChola commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return jobj?.get(QUERY)?.asJsonObject
Acá habría que definir jobj.get(Query) en una variable y después hacer return de (la nueva variable).asJsonObject??

2023-05-02 04:27 UTC, MateChola commented
Se solicitó el re request sin realizar los cambios relacionados con gson para poder tener un feedback de lo ya resuelto y poder mañana realizar los cambios si es que son necesarios

2023-05-02 14:31 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (items.isEmpty()) null else items[0]
Esto sigue sin modificar

2023-05-02 14:48 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            displayArtistInfo(artist)
El thread debe tener un solo metodo dentro suyo.. estas dos lineas es conveniente meterlas en una funcion, y en el thread llamar a esa funcion

2023-05-02 14:49 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return jobj?.get(QUERY)?.asJsonObject
si

2023-05-03 12:04 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        while (cursor.moveToNext()) {
solo necesitamos el primer elemento... no hacer while

2023-05-03 12:08 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        open(intent.getStringExtra(ARTIST_NAME_EXTRA).toString())
sobra el parametro

2023-05-03 12:12 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        setContentView(R.layout.activity_other_info)
initProperties... inicializan todo junto

2023-05-03 12:15 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getJobj(gson: Gson, callResponse: Response<String>): JsonObject? {
revisen el nombre de esta funcion

2023-05-03 12:18 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun getArtistInfoShell(artistName: String): String {
ojo con los shells

2023-05-03 12:18 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            e1.printStackTrace()
no imprimir...

2023-05-04 19:16 UTC, Luchyluz approved these changes
terminado

2023-05-04 19:17 UTC, merged