Clean mvp
elagarrigue/AyDS23-Winchester1 pull request #7
Opened 2023-05-11 01:40 UTC by MateChola

Se aplicó la arquitectura MVP al paquete full logic, respetando los principios SOLID y Clean Code

2023-05-11 19:47 UTC, elagarrigue requested changes
- Mejorar la descripción del PR
- Diagrama: db y el servicio externo van afuera de moredetails. Falta la dependencia indirecta presenter a view. Faltan detalles en data local y external.

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/OtherInfoView.kt
> +    fun displayArtistInfo(artist: OtherInfoUiState)
No deberían estar en la interfaz (rompe segregación de interfaces)

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/OtherInfoView.kt
> +private const val WIKIPEDIA_LOGO = "https://upload.wikimedia.org/wikipedia/commons/8/8c/Wikipedia-logo-v2-es.png"
Debería estar en UI State

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/OtherInfoView.kt
> +    override fun setPresenter(presenterInj: MoreDetailsPresenter) {
sufijo `Inj` no descriptivo, eliminar del nombre

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/OtherInfoView.kt
> +        loadImage(WIKIPEDIA_LOGO)
debería ser `artist.wikipediaLogo`

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +    private val format: InfoSongFormat,
```suggestion
    private val infoSongFormat: InfoSongFormat,
```

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +class MoreDetailsPresenterImpl(
internal

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +            uiStateSubject.notify(uiState)
otro nivel de abstracción, mover a subfuncion

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +        return OtherInfoUiState("",info, artist?.wikipediaUrl)
```suggestion
        return OtherInfoUiState("",info, artist.wikipediaUrl)
```

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenter.kt
> +        return OtherInfoUiState("",info, artist?.wikipediaUrl)
El logo se está mandando vacío, incorrecto.

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/InfoSongFormat.kt
> +            is Artist.WikipediaArtist ->
siempre entra por este camino.. No se está manejando el case empty result

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/ArtistRepository.kt
> +interface ArtistRepository {
mover a un paquete repository

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/domain/ArtistRepository.kt
> +    fun getArtist(artistName: String): Artist.WikipediaArtist
Debería devolver Artist ya q puede ser empty artist

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/ArtistRepositoryImpl.kt
> +            val wikipediaUrl = wikipediaTrackService.getArticleUrl(artistName)
debería ser una sola llamada, retornar el artista

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/ArtistRepositoryImpl.kt
> +        } catch (e1: IOException){""}
en caso de excepción debería retornar empty artist

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/local/sqldb/WikipediaLocalStorageImpl.kt
> +private const val DB_VERSION = 1
Mover a clase de constantes. Ver home.

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/local/sqldb/WikipediaLocalStorageImpl.kt
> +
diferente nivel de abstracción, ver home

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/external/WikipediaTrackService.kt
> +interface WikipediaTrackService {
`Track` es un concepto de song. Usar "Article"

2023-05-11 19:47 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/external/tracks/WikipediaAPI.java
>  public interface WikipediaAPI {
transformar a kotlin

2023-05-14 21:36 UTC, MateChola commented on app/src/main/java/ayds/winchester/songinfo/moredetails/presentation/OtherInfoView.kt
> +        artistInfoTextView = findViewById(R.id.textPane2)
Como deberíamos cambiar el nombre de findViewbyId, pq es un método externo, le tendríamos que hacer rename al método??

2023-05-15 21:02 UTC, elagarrigue requested changes
- Mejorar la descripción del PR, explicar con más detalle qué se hizo

2023-05-15 21:02 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/local/sqldb/WikipediaLocalStorageImpl.kt
> +private const val DB_VERSION = 1
mover a constantes

2023-05-15 21:02 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/moredetails/data/local/sqldb/WikipediaLocalStorageImpl.kt
> +    private val projection = arrayOf(
variable no utilizada

2023-05-16 18:17 UTC, elagarrigue approved these changes
Ahí quedó 👍🏽

2023-05-16 18:18 UTC, merged