Unit testing
elagarrigue/AyDS23-Winchester1 pull request #8
Opened 2023-05-18 01:14 UTC by MateChola

Se arreglaron los test unitarios del paquete home para su correcto funcionamiento. también se implementaron los test unitarios para el paquete moredatails. Los tests implementados son MoreDetailsPresenterTest (que testea la clase MoreDetailsPresenter con el 100% de las lineas), InfoSongFormatTest (que testea la clase InfoSongFormat con el 100% de las lineas) y ArtistRepositoryTest (que testea la clase ArtistRepository con el 100% de las lineas).

2023-05-18 21:20 UTC, Luchyluz commented on app/src/test/java/ayds/winchester/songinfo/home/view/SongDescriptionHelperTest.kt
> +    private val songDescriptionHelper by lazy { SongDescriptionHelperImpl(ReleaseDateFactoryImpl()) }
Si se instancia la dependencia no es unit test (y no cumple con ID). Hacer un mock del factory.

2023-05-18 21:20 UTC, Luchyluz requested changes
una ultima cosita

2023-05-18 21:46 UTC, MateChola commented
Profe, que más falta?? Porque quedó el comentario y creo que no lo terminaste.
Es para hacerlo hoy y ya poder dedicarnos mañana en la siguiente etapa.
Gracias

2023-05-18 21:58 UTC, Luchyluz commented
> Profe, que más falta?? Porque quedó el comentario y creo que no lo terminaste. Es para hacerlo hoy y ya poder dedicarnos mañana en la siguiente etapa. Gracias

Hola, en SongDescriptionHelperTest hice un comentario, deben hacer un mocck

2023-05-18 22:22 UTC, MateChola commented
Ah buenísimo, pensé que había algo más

2023-05-24 12:06 UTC, Luchyluz approved these changes

2023-05-24 12:06 UTC, merged